#pragma once
#include "submodules/wireguard-tools/src/ctype.h"
#include "submodules/wireguard-tools/src/ipc.h"
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
