config:
  log-path: *log-path
  max-parallel-commands: 5
  replica-replace-pattern: '%'
  show-failure-report: yes
  ignore-failure: no
  show-task-times: true
  show-failure-report: true
  show-summary-errors: true
  show-summary-steps: true
  show-summary-times: true
  stop-on-failure: true
  show-summary-footer: true
