include submodules/c_deps/etc/tools.mk
include submodules/c_deps/etc/entr.mk
include submodules/c_deps/etc/introspect.mk
include submodules/c_deps/etc/muon.mk
include submodules/c_deps/etc/meson.mk
include submodules/c_deps/etc/uncrustify.mk
include submodules/c_deps/etc/clean.mk
include submodules/c_deps/etc/loc.mk
include submodules/c_deps/etc/fzf.mk
include submodules/c_deps/etc/bashful.mk
include submodules/c_deps/etc/git.mk
